# -*- coding: utf-8 -*-
"""Shalini_AD_Paper1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwscpi61j5yS6LZuRU5vmhFlPvbTMoCV
"""

from google.colab import drive
drive.mount('/content/drive')

ADNI_ROOT = "/content/drive/MyDrive/ADNI1_Annual 2 Yr 3T"   # change if needed
CSV_PATH = "/content/drive/MyDrive/ADNI1_Annual_2_Yr_3T_5_14_2026.csv"  # change if needed
PROJECT_ROOT = "/content/drive/MyDrive/adni_3dresnet_cbam"

import os

os.makedirs(PROJECT_ROOT, exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/metadata", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/checkpoints", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/attention_maps", exist_ok=True)
os.makedirs(f"{PROJECT_ROOT}/outputs", exist_ok=True)

print("PROJECT_ROOT =", PROJECT_ROOT)

!pip -q install monai nibabel pandas scikit-learn matplotlib tqdm medcam

import pandas as pd

df = pd.read_csv(CSV_PATH)
print(df.head())
print(df.columns.tolist())
print("Total rows:", len(df))

df = df.copy()

mask = (
    (df["Modality"] == "MRI") &
    (df["Type"] == "Pre-processed") &
    (df["Format"].str.contains("NiFTI", case=False, na=False)) &
    (df["Description"].str.contains("MPR", case=False, na=False)) &
    (df["Description"].str.contains("N3", case=False, na=False))
)

df = df[mask].copy()
df = df[df["Group"].isin(["CN", "MCI", "AD"])].copy()

print(df["Group"].value_counts())
print(df[["Image Data ID", "Subject", "Group", "Visit", "Description"]].head())

import os
import re

nii_files = []
for root, _, files in os.walk(ADNI_ROOT):
    for f in files:
        if f.lower().endswith(".nii") or f.lower().endswith(".nii.gz"):
            nii_files.append(os.path.join(root, f))

print("Found NIfTI files:", len(nii_files))
print(nii_files[:5])

pattern = re.compile(r'(I\d+)')
id_to_path = {}

for path in nii_files:
    fname = os.path.basename(path)
    matches = pattern.findall(fname)
    if matches:
        image_id = matches[-1]
        id_to_path[image_id] = path

print("Matched image IDs from filenames:", len(id_to_path))

label_map = {"CN": 0, "MCI": 1, "AD": 2}

records = []
for _, row in df.iterrows():
    image_id = str(row["Image Data ID"]).strip()
    if image_id in id_to_path:
        records.append({
            "image_path": id_to_path[image_id],
            "label": label_map[row["Group"]],
            "group": row["Group"],
            "subject": row["Subject"],
            "visit": row["Visit"],
            "image_id": image_id,
            "description": row["Description"]
        })

meta_df = pd.DataFrame(records)
print("Matched rows:", len(meta_df))
print(meta_df.head())

meta_path = f"{PROJECT_ROOT}/metadata/meta_all.csv"
meta_df.to_csv(meta_path, index=False)
print("Saved:", meta_path)

from sklearn.model_selection import train_test_split

subjects = meta_df[["subject", "group"]].drop_duplicates()

train_sub, temp_sub = train_test_split(
    subjects,
    test_size=0.30,
    stratify=subjects["group"],
    random_state=42
)

val_sub, test_sub = train_test_split(
    temp_sub,
    test_size=0.50,
    stratify=temp_sub["group"],
    random_state=42
)

train_df = meta_df[meta_df["subject"].isin(train_sub["subject"])].reset_index(drop=True)
val_df   = meta_df[meta_df["subject"].isin(val_sub["subject"])].reset_index(drop=True)
test_df  = meta_df[meta_df["subject"].isin(test_sub["subject"])].reset_index(drop=True)

train_csv = f"{PROJECT_ROOT}/metadata/train.csv"
val_csv   = f"{PROJECT_ROOT}/metadata/val.csv"
test_csv  = f"{PROJECT_ROOT}/metadata/test.csv"

train_df.to_csv(train_csv, index=False)
val_df.to_csv(val_csv, index=False)
test_df.to_csv(test_csv, index=False)

print(len(train_df), len(val_df), len(test_df))
print(train_df["group"].value_counts())
print(val_df["group"].value_counts())
print(test_df["group"].value_counts())

import torch
from monai.transforms import (
    Compose, LoadImaged, EnsureChannelFirstd, Orientationd,
    Spacingd, ScaleIntensityRangePercentilesd, CropForegroundd,
    Resized, RandFlipd, RandRotate90d, RandAffined, EnsureTyped
)
from monai.data import Dataset, DataLoader

IMAGE_SIZE = (128, 128, 128)

def get_transforms(train=True):
    if train:
        return Compose([
            LoadImaged(keys=["image"]),
            EnsureChannelFirstd(keys=["image"]),
            Orientationd(keys=["image"], axcodes="RAS"),
            Spacingd(keys=["image"], pixdim=(1.5, 1.5, 1.5), mode="bilinear"),
            ScaleIntensityRangePercentilesd(
                keys=["image"], lower=1, upper=99, b_min=0.0, b_max=1.0, clip=True
            ),
            CropForegroundd(keys=["image"], source_key="image"),
            Resized(keys=["image"], spatial_size=IMAGE_SIZE, mode="trilinear"),
            RandFlipd(keys=["image"], prob=0.5, spatial_axis=0),
            RandFlipd(keys=["image"], prob=0.5, spatial_axis=1),
            RandFlipd(keys=["image"], prob=0.5, spatial_axis=2),
            RandRotate90d(keys=["image"], prob=0.5, max_k=3),
            RandAffined(
                keys=["image"],
                prob=0.2,
                rotate_range=(0.1, 0.1, 0.1),
                scale_range=(0.1, 0.1, 0.1),
                mode="bilinear",
                padding_mode="border"
            ),
            EnsureTyped(keys=["image", "label"])
        ])
    return Compose([
        LoadImaged(keys=["image"]),
        EnsureChannelFirstd(keys=["image"]),
        Orientationd(keys=["image"], axcodes="RAS"),
        Spacingd(keys=["image"], pixdim=(1.5, 1.5, 1.5), mode="bilinear"),
        ScaleIntensityRangePercentilesd(
            keys=["image"], lower=1, upper=99, b_min=0.0, b_max=1.0, clip=True
        ),
        CropForegroundd(keys=["image"], source_key="image"),
        Resized(keys=["image"], spatial_size=IMAGE_SIZE, mode="trilinear"),
        EnsureTyped(keys=["image", "label"])
    ])

def dataframe_to_items(df):
    return [{"image": r["image_path"], "label": int(r["label"])} for _, r in df.iterrows()]

train_ds = Dataset(data=dataframe_to_items(train_df), transform=get_transforms(train=True))
val_ds   = Dataset(data=dataframe_to_items(val_df), transform=get_transforms(train=False))
test_ds  = Dataset(data=dataframe_to_items(test_df), transform=get_transforms(train=False))

train_loader = DataLoader(train_ds, batch_size=2, shuffle=True, num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=2, shuffle=False, num_workers=2, pin_memory=True)
test_loader  = DataLoader(test_ds, batch_size=1, shuffle=False, num_workers=2, pin_memory=True)

batch = next(iter(train_loader))
print(batch["image"].shape, batch["label"])

import torch.nn as nn
from monai.networks.nets import resnet50
from monai.networks.nets.resnet import ResNetBottleneck

class ChannelAttention3D(nn.Module):
    def __init__(self, in_planes, reduction=16):
        super().__init__()
        hidden = max(in_planes // reduction, 8)
        self.avg_pool = nn.AdaptiveAvgPool3d(1)
        self.max_pool = nn.AdaptiveMaxPool3d(1)
        self.mlp = nn.Sequential(
            nn.Conv3d(in_planes, hidden, kernel_size=1, bias=False),
            nn.ReLU(inplace=True),
            nn.Conv3d(hidden, in_planes, kernel_size=1, bias=False)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = self.mlp(self.avg_pool(x))
        max_out = self.mlp(self.max_pool(x))
        return self.sigmoid(avg_out + max_out)

class SpatialAttention3D(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        padding = kernel_size // 2
        self.conv = nn.Conv3d(2, 1, kernel_size=kernel_size, padding=padding, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x_cat = torch.cat([avg_out, max_out], dim=1)
        return self.sigmoid(self.conv(x_cat))

class CBAM3D(nn.Module):
    def __init__(self, channels, reduction=16, spatial_kernel=7):
        super().__init__()
        self.ca = ChannelAttention3D(channels, reduction)
        self.sa = SpatialAttention3D(spatial_kernel)

    def forward(self, x):
        x = x * self.ca(x)
        x = x * self.sa(x)
        return x

class ResNet50CBAM3D(nn.Module):
    def __init__(self, num_classes=3):
        super().__init__()
        self.backbone = resnet50(
            spatial_dims=3,
            n_input_channels=1,
            num_classes=num_classes,
            pretrained=False
        )
        self.cbam1 = CBAM3D(256)
        self.cbam2 = CBAM3D(512)
        self.cbam3 = CBAM3D(1024)
        self.cbam4 = CBAM3D(2048)

    def forward(self, x):
        x = self.backbone.conv1(x)
        x = self.backbone.bn1(x)
        x = self.backbone.act(x)
        x = self.backbone.maxpool(x)

        x = self.backbone.layer1(x); x = self.cbam1(x)
        x = self.backbone.layer2(x); x = self.cbam2(x)
        x = self.backbone.layer3(x); x = self.cbam3(x)
        x = self.backbone.layer4(x); x = self.cbam4(x)

        x = self.backbone.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.backbone.fc(x)
        return x

import numpy as np
import torch
from sklearn.metrics import accuracy_score, f1_score
from tqdm import tqdm

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

labels = train_df["label"].values
class_counts = np.bincount(labels, minlength=3)
class_weights = class_counts.sum() / (class_counts + 1e-6)
class_weights = class_weights / class_weights.sum() * 3
class_weights = torch.tensor(class_weights, dtype=torch.float32).to(device)

model = ResNet50CBAM3D(num_classes=3).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-5)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="max", factor=0.5, patience=3)

ckpt_path = f"{PROJECT_ROOT}/checkpoints/best_model.pth"
history_path = f"{PROJECT_ROOT}/outputs/history.csv"

best_f1 = 0.0
history = []

def evaluate(model, loader):
    model.eval()
    all_labels, all_preds = [], []
    total_loss = 0.0

    with torch.no_grad():
        for batch in loader:
            x = batch["image"].to(device)
            y = batch["label"].to(device)

            out = model(x)
            loss = criterion(out, y)

            pred = torch.argmax(out, dim=1)
            total_loss += loss.item() * x.size(0)

            all_labels.extend(y.cpu().numpy())
            all_preds.extend(pred.cpu().numpy())

    loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds, average="weighted")
    return loss, acc, f1

EPOCHS = 5

for epoch in range(EPOCHS):
    model.train()
    all_labels, all_preds = [], []
    total_loss = 0.0

    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}")
    for batch in pbar:
        x = batch["image"].to(device)
        y = batch["label"].to(device)

        optimizer.zero_grad()
        out = model(x)
        loss = criterion(out, y)
        loss.backward()
        optimizer.step()

        pred = torch.argmax(out, dim=1)
        total_loss += loss.item() * x.size(0)
        all_labels.extend(y.cpu().numpy())
        all_preds.extend(pred.detach().cpu().numpy())

        pbar.set_postfix(loss=float(loss.item()))

    train_loss = total_loss / len(train_loader.dataset)
    train_acc = accuracy_score(all_labels, all_preds)
    train_f1 = f1_score(all_labels, all_preds, average="weighted")

    val_loss, val_acc, val_f1 = evaluate(model, val_loader)
    scheduler.step(val_f1)

    history.append([epoch+1, train_loss, train_acc, train_f1, val_loss, val_acc, val_f1])

    print(f"\nEpoch {epoch+1}")
    print(f"Train Loss={train_loss:.4f} Acc={train_acc:.4f} F1={train_f1:.4f}")
    print(f"Val   Loss={val_loss:.4f} Acc={val_acc:.4f} F1={val_f1:.4f}")

    if val_f1 > best_f1:
        best_f1 = val_f1
        torch.save(model.state_dict(), ckpt_path)
        print("Saved best model.")

pd.DataFrame(
    history,
    columns=["epoch", "train_loss", "train_acc", "train_f1", "val_loss", "val_acc", "val_f1"]
).to_csv(history_path, index=False)

print("Best val F1:", best_f1)

from sklearn.metrics import confusion_matrix, classification_report

model.load_state_dict(torch.load(ckpt_path, map_location=device))
model.eval()

all_labels, all_preds = [], []

with torch.no_grad():
    for batch in test_loader:
        x = batch["image"].to(device)
        y = batch["label"].to(device)

        out = model(x)
        pred = torch.argmax(out, dim=1)

        all_labels.extend(y.cpu().numpy())
        all_preds.extend(pred.cpu().numpy())

print("Confusion Matrix:")
print(confusion_matrix(all_labels, all_preds))
print("\nClassification Report:")
print(classification_report(all_labels, all_preds, target_names=["CN", "MCI", "AD"], digits=4))

from medcam import medcam
from monai.transforms import Resized # Import Resized for the new transforms

# Clear previous model and optimizer from GPU memory if they exist
if 'model' in locals():
    del model
if 'optimizer' in locals():
    del optimizer
if 'criterion' in locals():
    del criterion
if 'scheduler' in locals():
    del scheduler

# Explicitly delete data loaders and datasets to free up GPU memory
if 'train_loader' in locals():
    del train_loader
if 'val_loader' in locals():
    del val_loader
if 'test_loader' in locals():
    del test_loader
if 'train_ds' in locals():
    del train_ds
if 'val_ds' in locals():
    del val_ds
if 'test_ds' in locals():
    del test_ds

torch.cuda.empty_cache()

# Initialize cam_model on CPU first
cam_model = ResNet50CBAM3D(num_classes=3)
# Load state_dict to CPU, then apply and move model to device
state_dict = torch.load(ckpt_path, map_location='cpu')
cam_model.load_state_dict(state_dict)
cam_model.to(device)
cam_model.eval()

# Define new image size and transforms specifically for CAM generation
CAM_IMAGE_SIZE = (64, 64, 64)

def get_cam_transforms():
    return Compose([
        LoadImaged(keys=["image"]),
        EnsureChannelFirstd(keys=["image"]),
        Orientationd(keys=["image"], axcodes="RAS"),
        Spacingd(keys=["image"], pixdim=(1.5, 1.5, 1.5), mode="bilinear"),
        ScaleIntensityRangePercentilesd(
            keys=["image"], lower=1, upper=99, b_min=0.0, b_max=1.0, clip=True
        ),
        CropForegroundd(keys=["image"], source_key="image"),
        Resized(keys=["image"], spatial_size=CAM_IMAGE_SIZE, mode="trilinear"), # Use smaller size
        EnsureTyped(keys=["image", "label"])
    ])

# Create a new test_loader for CAM with smaller image sizes
cam_test_ds = Dataset(data=dataframe_to_items(test_df), transform=get_cam_transforms())
cam_test_loader = DataLoader(cam_test_ds, batch_size=1, shuffle=False, num_workers=0, pin_memory=True) # Changed num_workers to 0

cam_model = medcam.inject(
    cam_model,
    backend="gcam",
    output_dir=f"{PROJECT_ROOT}/attention_maps",
    save_maps=True,
    layer="backbone.layer3" # Explicitly specify a later layer for less memory consumption
)

with torch.no_grad():
    for i, batch in enumerate(cam_test_loader): # Use cam_test_loader
        if i >= 50:   # generate for first 10 test scans
            break
        x = batch["image"].to(device)
        y = batch["label"].to(device)
        out = cam_model(x)
        pred = torch.argmax(out, dim=1)
        print(f"Sample {i}: true={int(y.item())}, pred={int(pred.item())}")

import nibabel as nib
import matplotlib.pyplot as plt
import numpy as np

sample_path = meta_df.iloc[0]["image_path"]
img = nib.load(sample_path).get_fdata()

z = img.shape[2] // 2
y = img.shape[1] // 2
x = img.shape[0] // 2

fig, axes = plt.subplots(1, 3, figsize=(15, 5))
axes[0].imshow(img[:, :, z], cmap="gray")
axes[0].set_title("Axial")
axes[1].imshow(img[:, y, :], cmap="gray")
axes[1].set_title("Coronal")
axes[2].imshow(img[x, :, :], cmap="gray")
axes[2].set_title("Sagittal")
for ax in axes:
    ax.axis("off")
plt.show()

import os

cam_dir = f"{PROJECT_ROOT}/attention_maps"
print("Attention maps directory:", cam_dir)

for root, dirs, files in os.walk(cam_dir):
    print("DIR:", root)
    for f in files[:10]:
        print("  ", f)
    break

import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt

cam_path = "/content/drive/MyDrive/adni_3dresnet_cbam/attention_maps/backbone.layer4/attention_map_7_0_0.nii.gz"
print("CAM path:", cam_path)

# choose the first test MRI (same order you used when generating maps)
sample_row = test_df.iloc[0]
mri_path = sample_row["image_path"]
print("MRI path:", mri_path)

mri_nii = nib.load(mri_path)
mri_vol = mri_nii.get_fdata()

cam_nii = nib.load(cam_path)
cam_vol = cam_nii.get_fdata()

print("MRI shape:", mri_vol.shape)
print("CAM shape:", cam_vol.shape)

import scipy.ndimage

def center_crop_to_match(src, target_shape):
    src_shape = np.array(src.shape)
    tgt_shape = np.array(target_shape)
    start = ((src_shape - tgt_shape) / 2).astype(int)
    end = start + tgt_shape
    slices = tuple(slice(s, e) for s, e in zip(start, end))
    return src[slices]

# adjust CAM to MRI shape if they differ
if cam_vol.shape != mri_vol.shape:
    print("Resizing CAM from", cam_vol.shape, "to", mri_vol.shape)
    # Calculate zoom factors to resize cam_vol to mri_vol.shape
    zoom_factors = [mri_vol.shape[i] / cam_vol.shape[i] for i in range(3)]
    cam_vol = scipy.ndimage.zoom(cam_vol, zoom_factors, order=1) # order=1 for bilinear interpolation

print("Aligned MRI shape:", mri_vol.shape)
print("Aligned CAM shape:", cam_vol.shape)

# normalize for visualization
mri_norm = mri_vol / (np.percentile(mri_vol, 99) + 1e-6)
cam_norm = cam_vol / (cam_vol.max() + 1e-6)

z = mri_norm.shape[2] // 2
y = mri_norm.shape[1] // 2
x = mri_norm.shape[0] // 2

fig, axes = plt.subplots(2, 3, figsize=(15, 8))

# row 1: MRI
axes[0, 0].imshow(mri_norm[:, :, z].T, cmap="gray", origin="lower")
axes[0, 0].set_title("Axial MRI (mid)")

axes[0, 1].imshow(mri_norm[:, y, :].T, cmap="gray", origin="lower")
axes[0, 1].set_title("Coronal MRI (mid)")

axes[0, 2].imshow(mri_norm[x, :, :].T, cmap="gray", origin="lower")
axes[0, 2].set_title("Sagittal MRI (mid)")

# row 2: MRI + Grad-CAM overlay
axes[1, 0].imshow(mri_norm[:, :, z].T, cmap="gray", origin="lower")
axes[1, 0].imshow(cam_norm[:, :, z].T, cmap="jet", alpha=0.5, origin="lower")
axes[1, 0].set_title("Axial Grad-CAM")

axes[1, 1].imshow(mri_norm[:, y, :].T, cmap="gray", origin="lower")
axes[1, 1].imshow(cam_norm[:, y, :].T, cmap="jet", alpha=0.5, origin="lower")
axes[1, 1].set_title("Coronal Grad-CAM")

axes[1, 2].imshow(mri_norm[x, :, :].T, cmap="gray", origin="lower")
axes[1, 2].imshow(cam_norm[x, :, :].T, cmap="jet", alpha=0.5, origin="lower")
axes[1, 2].set_title("Sagittal Grad-CAM")

for ax in axes.ravel():
    ax.axis("off")

plt.tight_layout()
plt.show()